services:
  database:
    image: mariadb:latest
    container_name: music_store-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: music_store
      MYSQL_USER: seller
      MYSQL_PASSWORD: makeMoney123
    ports:
      - "3306:3306"
    volumes:
      - music_store_data:/var/lib/mysql
    networks:
      - music_store_network

  frontend:
    image: nginx:alpine
    container_name: music_store-web
    restart: always
    ports:
    - "80:80"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    #network_mode: "host"
    volumes:
      - ../swi1_vlasak_vjacka_frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - music_store_network

volumes:
  music_store_data:

networks:
  music_store_network:
